#!/usr/bin/env python2

import tempfile
import shutil
import stat
import getpass
import sys
import subprocess
import os
import re
import hashlib
import datetime

import config as cfg

class Main(object):

    installScript="""#!/bin/sh
CURR_DIR="$PWD"
DOLMADE_FNAME="$(ls *.dme|head -n1)"
DOLMADE_NAME="$(echo $DOLMADE_FNAME|sed 's/\.dme$//')"
INST_DIR="$HOME/Dolmades/"""+cfg.VERSION+"""/$DOLMADE_NAME"

export UDOCKER_TARBALL="$CURR_DIR/udocker-tarball-1.1.3.tar.gz"

echo "Installing $DOLMADE_NAME into $INST_DIR..."

mkdir -p "$INST_DIR/cli"
mkdir -p "$INST_DIR/res"

cp -p "$CURR_DIR/cli/dolmades" "$INST_DIR/cli"
cp -p "$CURR_DIR/cli/udocker" "$INST_DIR/cli"
cp -p "$CURR_DIR/cli/prettyprint.py" "$INST_DIR/cli"
cp -p "$CURR_DIR/license.txt" "$INST_DIR"

cat "$CURR_DIR/cli/config.py" | sed "s#^DOLMADES_PATH = HOME + '/.dolmades-' + VERSION#DOLMADES_PATH = '"$INST_DIR"/.dolmades'#" > "$INST_DIR/cli/config.py"
echo >> "$INST_DIR/cli/config.py"
echo "BOXED_PATH=\'$INST_DIR\'" >> "$INST_DIR/cli/config.py"

cd "$INST_DIR/cli"
./dolmades import "$CURR_DIR/$DOLMADE_FNAME"
./dolmades serve $DOLMADE_NAME

echo "Installation completed!"
"""

    defaultLicense="""===DOLMADES LICENSE TEMPLATE===
This Dolmade contains installable Windows software and has been created using Dolmades v"""+cfg.VERSION+""". 
It ships bundled with the following software components licensed under the following open source licenses:

 * Dolmades   - https://github.com/dolmades/dolmades-cli -- Apache 2.0
 * Wine       - https://winehq.org                       -- LGPL v2.1
 * UDocker    - https://github.com/indigo-dc/udocker     -- Apache 2.0
 * Proot      - https://proot.me                         -- GPL v2.0
 * Ubuntu     - https://www.ubuntu.com                   -- https://www.ubuntu.com/licensing
 * Yad        - https://github.com/v1cont/yad            -- GPL v3.0
 * ImageMagic -- https://raw.githubusercontent.com/ImageMagick/ImageMagick/master/LICENSE
 * Python 2.7 -- https://www.python.org/download/releases/2.7/license/

Furthermore, the Windows software shipping with this Dolmade contains the following licenses:
 * Unknown! Please add it here!
"""

    def start(self):
        try:
            if (sys.argv[1]=="-h" or sys.argv[1]=="--help"):
                print("Usage: "+sys.argv[0]+" dolmadename [licensefile]")
                return
            dolmadeName = sys.argv[1]
        except:
            print("Usage: "+sys.argv[0]+" dolmadename [licensefile]")
            return

        workdir = tempfile.mkdtemp()
        
        try:
            licenseFile = sys.argv[2]
            shutil.copy(licenseFile, workdir+"/license.txt")
            print("Using license file given as argument")
        except:
            print("No license file argument, trying to find the license in the meta data")
            try:
                shutil.copy(metaDir+"/"+licenseFile, "./license.txt")
                print("Using license from meta data")
            except:
                print("Warning: no license found, we do not allow boxing without a license!\nTherefore a default license will be shipped!\nThis is NOT recommended!")
                f=open(workdir+"/license.txt",'w')
                f.write(self.defaultLicense)
                f.close()

        cwd = os.getcwd()
        os.chdir(workdir)

        os.mkdir("./cli", 0755)
        shutil.copy(cfg.SELF_PATH+"/dolmades","./cli/dolmades")
        shutil.copy(cfg.SELF_PATH+"/udocker","./cli/udocker")
        shutil.copy(cfg.SELF_PATH+"/config.py","./cli/config.py")
        shutil.copy(cfg.SELF_PATH+"/prettyprint.py","./cli/prettyprint.py")

        metaDir=cfg.DOLMADES_PATH+"/containers/"+os.readlink(cfg.DOLMADES_PATH+'/containers/'+dolmadeName)+"/ROOT/.dolmades/"
        cmd=cfg.SELF_PATH+"/dolmades export '"+dolmadeName+"'"
        print(cmd)
        subprocess.call(cmd, shell=True, close_fds=True)

        # retrieve makeself 2.4.0 and revert commit 48304a7d9a423a54d9a92c3ac5701f91e83b454c to fix progress indication
        cmd="wget https://dolmades.org/mirror/udocker/udocker-tarball-1.1.3.tar.gz && \
             wget https://raw.githubusercontent.com/megastep/makeself/release-2.4.0/makeself.sh && \
             wget https://raw.githubusercontent.com/megastep/makeself/release-2.4.0/makeself-header.sh && \
             sed -i 's#dd ibs=\\\$offset skip=1 2>/dev/null#dd bs=\\\$offset count=0 skip=1 2>/dev/null#' makeself-header.sh && \
             sed -i 's#| more#| more -d#' makeself-header.sh"

        print(cmd)
        subprocess.call(cmd, shell=True, close_fds=True)

        f=open("./install.sh",'w')
        f.write(self.installScript)
        f.close()
        st=os.stat("./install.sh")
        os.chmod("./install.sh", st.st_mode|stat.S_IEXEC)

        packagingDate=datetime.datetime.fromtimestamp(os.path.getmtime(metaDir)).isoformat()
        cmd="sh makeself.sh --packaging-date '"+packagingDate+"' --license ./license.txt "+workdir+" "+cwd+"/"+dolmadeName+".dme.sh '"+dolmadeName+" packaged by Dolmades v"+cfg.VERSION+" -- https://dolmades.org' ./install.sh"
        print(cmd)
        subprocess.call(cmd, shell=True, close_fds=True)

        shutil.rmtree(workdir)
        print("Done!")

if __name__ == "__main__":
    sys.exit(Main().start())
