#!/usr/bin/env python

import sys
import subprocess
import os

__author__ = "stefan.kombrink@gmail.com"
__credits__ = ["UDocker https://github.com/indigo-dc/udocker",
               "PRoot http://proot.me",
               "runC https://runc.io"]
__license__ = "Licensed under the Apache License, Version 2.0"
__version__ = "0.1"
__date__ = "2018"

# Python version major.minor
PY_VER = "%d.%d" % (sys.version_info[0], sys.version_info[1])
START_PATH = os.path.dirname(os.path.realpath(sys.argv[0]))

class Dolmade(object):
    repoDir="~/.udocker"
    udocker=START_PATH + "/udocker"
    def __init__(self):
        print "init"

    def dumpComment(self, cmdp):
        if (False):
            print(cmdp)

    def setupDolmade(self, cmdp):
        print("Setting the Dolmade Name to ")
        print(cmdp)

    def setupBase(self, cmdp):
        print("Setting the Base Docker Image to ")
        print(cmdp)

    def setupIngredient(self, cmdp):
        print("Setting up ingredient ")
        print(cmdp)

    def run(self, cmdp):
        print("Running as user...")
        print(cmdp)
        status = subprocess.call("sleep 5", shell=True, close_fds=True)

    def runRoot(self, cmdp):
        print("Running as root...")
        print(cmdp)

    def icon(self, cmdp):
        print("Selecting icon...")

    def finalize(self):
        print("Installing the sucessfully built dolmade...")

class Main(object):
    dolmade = Dolmade()

    def execute(self):
        """all supported dolmade commands"""
        cmds = { '#': self.dolmade.dumpComment,
                 'DOLMADE': self.dolmade.setupDolmade, 
                 'BASE': self.dolmade.setupBase,
                 'INGREDIENT': self.dolmade.setupIngredient,
                 'RUN': self.dolmade.run,
                 'RUNROOT': self.dolmade.runRoot,
                 'ICON': self.dolmade.icon }
        if (len(sys.argv)==1):
            inputFileName = os.getcwd() + "/Dolmadefile"
        else:
            inputFileName = sys.argv[1];

        try:
            with open(inputFileName, "r") as dolmadeFile:
                cmdarg = ""
                token = list()
                for line in dolmadeFile:
                    line = line.strip().replace('#','# ')
                    if (line.endswith('\\')): 
                        token += line.replace('\\','').strip().split(' ')
                        continue
                    if line: token += (line.split(' '))
                    if (len(token)>=1):
                        instr = token[0]
                        cmdarg = token[0:len(token)]
                        if (instr in cmds):
                            cmds[instr](cmdarg)
                        else:
                            raise Exception('Unknown instruction ' + instr + ":" + cmdarg)
                    token = list()

        except (IOError, OSError):
            print("ERROR: Cannot open " + inputFileName)

    def start(self):
        """Program start and exception handling"""
        try:
            exit_status = self.execute()
        except (KeyboardInterrupt, SystemExit):
            self.cleanup()
            return 1
        except:
            self.cleanup()
            raise
        else:
            self.cleanup()
            return exit_status

    def cleanup(self):
        print("Deleting all temporary files...")


if __name__ == "__main__":
    sys.exit(Main().start())
