#!/usr/bin/env python

import shutil
import stat
import getpass
import sys
import subprocess
import os
import re
import hashlib
from PIL import Image
import pycurl

__author__ = "stefan.kombrink@gmail.com"
__credits__ = ["UDocker https://github.com/indigo-dc/udocker",
               "PRoot http://proot.me",
               "runC https://runc.io"]
__license__ = "Licensed under the Apache License, Version 2.0"
__version__ = "0.1"
__date__ = "2018"

# Python version major.minor
PY_VER = "%d.%d" % (sys.version_info[0], sys.version_info[1])
START_PATH = os.path.dirname(os.path.realpath(sys.argv[0]))
DOLMADES_PATH = os.path.expanduser('~')+'/.dolmades'

REPO_PATH = DOLMADES_PATH + "/repo"
ICON_PATH = DOLMADES_PATH + "/icons"
INST_PATH = DOLMADES_PATH + "/install"

try:
    DESK_PATH = subprocess.check_output(['xdg-user-dir', 'DESKTOP']).strip()
except:
    DESK_PATH = os.path.expanduser("~/Desktop")

def createDirectories():
    if (not os.path.exists(DOLMADES_PATH)):
        os.mkdir(DOLMADES_PATH, 0755)
    try:
        if (os.path.exists(REPO_PATH)):
            os.rmdir(REPO_PATH)
    except:
        print(REPO_PATH+" not empty, do not delete...")
    if (not os.path.exists(ICON_PATH)):
        os.mkdir(ICON_PATH, 0755)
    if (not os.path.exists(INST_PATH)):
        os.mkdir(INST_PATH, 0755)

class Ingredient(object):

    def __init__(self, h, fn, dn, u):
        self.sha256hash = h
        self.displayName = dn
        self.fileName = fn
        self.urls = list()
        self.local_urls = list()
        self.gog_urls = list()
        self.addUrl(u)

    def addUrl(self, u):
        if (u.startswith('gog://')):
            self.gog_urls.append(u)
            return

        if (u.startswith('file://')):
            self.local_urls.append(u)
            return

        self.urls.append(u)


    def downloadProgress(self, download_t, download_d, upload_t, upload_d):
        try:
            frac = float(download_d)/float(download_t)
        except:
            frac = 0
        sys.stdout.write("\r%s %3i%%" % ("Download:", frac*100)  )
        if (frac > 99.999):
            print('')

    def checklocal(self):
        try:
            sha256 = hashlib.sha256()
            block_size=65536
            if not os.path.isfile(INST_PATH + "/" + self.fileName):
                print('File has yet to be retrieved!')
                return False
            with open(INST_PATH + "/" + self.fileName, 'rb') as f:
                for block in iter(lambda: f.read(block_size), b''):
                    sha256.update(block)
            if (sha256.hexdigest() != self.sha256hash):
                print('Error: invalid hash sum for ingredient')
                return False
            else:
                print('Good: hash sum correct!')
                return True
        except Exception as error:
            print("Caught " + repr(error))
            return False

    def retrieve(self):
        if self.checklocal():
            return True

        # try to use local copy of the ingredient if available
        for u in self.local_urls:
            try:
                print("Using local copy of " + self.fileName + " from " + u)
                shutil.copy(u.replace('file://',''), INST_PATH + "/" + self.fileName)
                if self.checklocal():
                    return True
                else:
                    continue
            except Exception as error:
                print(error)
                continue
        
        # try to obtain file via GOG downloader
        for u in self.gog_urls:
            try:
                print("Using a valid GOG account to download " + u + " as " + self.fileName)
                raise NotImplemented
            except Exception as error:
                print(error)
                continue

        # try to retrieve ingredient from remote locations
        for u in self.urls:
            try:
                print("Retrieving " + self.fileName + " from " + u)
                with open(INST_PATH + "/" + self.fileName, 'wb') as f:
                    c = pycurl.Curl()
                    c.setopt(c.VERBOSE, False)
                    c.setopt(pycurl.HEADER, 0)
                    c.setopt(pycurl.FOLLOWLOCATION, 1)
                    c.setopt(pycurl.MAXREDIRS, 5)
                    c.setopt(pycurl.CONNECTTIMEOUT, 30)
                    c.setopt(pycurl.TIMEOUT, 300)
                    c.setopt(pycurl.NOSIGNAL, 1)
                    c.setopt(pycurl.NOPROGRESS, 0)
                    c.setopt(pycurl.PROGRESSFUNCTION, self.downloadProgress)
                    c.setopt(c.URL, u)
                    c.setopt(c.WRITEDATA, f)
                    c.perform()
                    c.close()
                if self.checklocal():
                    return True   
                else:
                    continue
            except Exception as error:
                print('\nCaught: ' + repr(error))
                continue

        return False


class Dolmade(object):

    udocker=START_PATH + '/udocker'
    iconfn = None
    installDir=START_PATH + '/install'
    name = None
    sha256 = None
    ingredients = []
    runs = []

    def __init__(self):
        pass

    def dumpComment(self, cmdp):
        if (False):
            print(cmdp)

    def setupDolmade(self, cmdp):
        self.name = ' '.join(cmdp)
        print("Setting Dolmade Name to " + self.name)

    def setupBase(self, cmdp):
        self.baseImg = ''.join(cmdp)
        print("Setting Base Docker Image to " + self.baseImg)

    def setupIngredient(self, cmdp):
        h = cmdp[0]
        fn = cmdp[1]
        dn = cmdp[2]
        u = cmdp[3]

        sys.stdout.write("Adding Ingredient " + dn + ":" + fn + ":" + h + ":" + u)
        ingr = Ingredient(h,fn,dn,u)
        
        for i in range(4,len(cmdp)):
            isInvalid = True
            for url_pf in ['http://', 'https://', 'ftp://', 'file://', 'gog://']:
                if (cmdp[i].startswith(url_pf)): 
                    sys.stdout.write(":" + cmdp[i])
                    ingr.addUrl(cmdp[i])
                    isInvalid = False
            if isInvalid:
                raise Exception("Malformed Url "+cmdp[i])

        self.ingredients.append(ingr)
        print("")

    def detectInstallation(self):
        pass
        # find /wineprefix -name *.lnk -exec python /wineprefix/dumplnk.py {} \;

    def run(self, cmdp):
        print("Running as User:" + ' '.join(cmdp))
        self.runs.append(('user',cmdp))

    def runRoot(self, cmdp):
        print("Running as Root:" + ' '.join(cmdp))
        self.runs.append(('root',cmdp))

    def icon(self, cmdp):
        self.iconfn = ''.join(cmdp)
        print("Selecting Icon:" + self.iconfn)

    def setTarget(self, cmdp):
        self.runs.append(('setTarget', cmdp))
        print("Determine target path by running:" + ' '.join(cmdp))

    def setTargetBind(self, cmdp):
        targetBinds.append(cmdp)
        print("Bind mount for target run:" + join(cmdp))
        
    def build(self):
        print("Performing the dolmade build...")
        for i in self.ingredients: 
            i.retrieve()

        cmd = self.udocker + " mkrepo " + REPO_PATH
        print cmd
        try:
            outp = subprocess.check_output(cmd, shell=True, close_fds=True, stderr=subprocess.STDOUT)
        except:
            print("Repo exists already")

        cmd = self.udocker + " --repo=" + REPO_PATH + " pull " + self.baseImg
        print cmd
        subprocess.call(cmd, shell=True, close_fds=True)

        cmd = self.udocker + " --repo=" + REPO_PATH + " create " + self.baseImg
        print("Installing the sucessfully built dolmade...")
        sha256 = subprocess.check_output(cmd, shell=True, close_fds=True)

        cmd = self.udocker + " --repo=" + REPO_PATH + " rm " + self.name
        print(cmd)
        subprocess.call(cmd, shell=True, close_fds=True)

        cmd = self.udocker + " --repo=" + REPO_PATH + " name " + sha256.strip() + " " + self.name
        print(cmd)
        subprocess.call(cmd, shell=True, close_fds=True)

        self.target = None
        self.targetPath = None
        self.sha256 = sha256.strip()

        for r in self.runs:
            (u,c) = r
            if (u == 'root'):
                cmd = self.udocker + " --repo=" + REPO_PATH + " run --volume=" + INST_PATH + ":/install --user=root --volume="+os.path.expanduser("~")+"/.Xauthority --hostenv --dri " + self.name + " " + "bash -c 'cd /install && " + ' '.join(c) + "'"
                subprocess.call(cmd, shell=True, close_fds=True)
            if (u == 'user'):
                cmd = self.udocker + " --repo=" + REPO_PATH + " run --volume=" + INST_PATH + ":/install --user="+getpass.getuser()+" --volume="+os.path.expanduser("~")+"/.Xauthority --hostenv --dri " + self.name + " " + "bash -c 'cd /install && " + ' '.join(c) + "'"
                print(cmd)
                subprocess.call(cmd, shell=True, close_fds=True)
            if (u == 'setTarget'):
                cmd = self.udocker + " --quiet --repo=" + REPO_PATH + " run --user="+getpass.getuser()+" --hostenv " + self.name + " bash -c '" + ' '.join(c) + "'"
                print(cmd)
                try:
                    outp = subprocess.check_output(cmd, shell=True, close_fds=True, stderr=subprocess.STDOUT)
                    outp = outp.strip()
                    self.target = ''.join(outp.split('/')[-1])
                    self.targetPath = '/'.join(outp.split('/')[:-1])
                except:
                    print("ERROR: could not determine target path!")

        if (self.target):
            print("Predefined target is "+self.target+", target path is "+self.targetPath)
        else:
            print("Trying to autodetect target...")
            cmd = self.udocker + " --quiet --repo=" + REPO_PATH + " run --user="+getpass.getuser()+" --volume=" + REPO_PATH+ "/containers/" + self.sha256 + "/ROOT/wineprefix:/wineprefix --hostenv dolmades-runtime /usr/local/bin/findGOGtarget.sh"
            try:
                print(cmd)
                outp = subprocess.check_output(cmd, shell=True, close_fds=True, stderr=subprocess.STDOUT)
                outp = outp.strip()
                self.target = ''.join(outp.split('/')[-1])
                self.targetPath = '/'.join(outp.split('/')[:-1])
                print("Autodetected target is "+self.target+", target path is "+self.targetPath)
            except:
                print("ERROR: could not determine target path!")

        im = Image.open(INST_PATH+"/"+self.iconfn)
        im.save(ICON_PATH+"/"+self.name+".png")
        #shutil.copy(INST_PATH+"/"+self.iconfn,ICON_PATH+"/"+self.name+".png")

        with open(DESK_PATH + "/" + self.name + ".desktop", "w") as text_file:
            text_file.write("[Desktop Entry]\nEncoding=UTF-8\nValue=1.0\nType=Application\n")
            text_file.write("Name="+self.name.replace('_',' ')+"\nGenericName="+self.name.replace('_',' ')+"\nComment=" + self.name.replace('_',' ')+"\n")
            text_file.write("Icon="+os.path.expanduser("~")+"/.dolmades/icons/"+self.name+".png"+"\n")
            text_file.write("Exec="+self.udocker+" --repo="+REPO_PATH + " run --user="+getpass.getuser()+" --volume="+os.path.expanduser("~")+"/.Xauthority --hostenv --dri " + self.name + " " + "bash -c '"+'cd "'+self.targetPath+'" && wine "'+self.target+'"'+"'\n")
            text_file.write("Categories=Game;\n")
            text_file.write("Path="+os.path.expanduser("~")+"\n")

        st = os.stat(DESK_PATH + "/" + self.name + ".desktop")
        os.chmod(DESK_PATH + "/" + self.name + ".desktop", st.st_mode | stat.S_IEXEC)

class Main(object):
    dolmade = Dolmade()

    def executeCmd(self, cmdarg):
        """all supported commands"""
        cmds = { '': self.dolmade.dumpComment,
                 '#': self.dolmade.dumpComment,
                 'DOLMADE': self.dolmade.setupDolmade, 
                 'BASE': self.dolmade.setupBase,
                 'INGREDIENT': self.dolmade.setupIngredient,
                 'RUNUSER': self.dolmade.run,
                 'RUNROOT': self.dolmade.runRoot,
                 'ICON': self.dolmade.icon,
                 'SETTARGET': self.dolmade.setTarget,
                 'TARGETBIND': self.dolmade.setTargetBind }

        if len(cmdarg)<1:
            return

        cmd = cmdarg[0]
        arg = cmdarg[1:len(cmdarg)]

        if (cmd in cmds):
            cmds[cmd](arg)
        else:
            raise Exception('Unknown instruction ' + cmd + ":" + " ".join(cmdarg))


    def execute(self):
        if (len(sys.argv)==1):
            inputFileName = os.getcwd() + "/Dolmadefile"
        else:
            inputFileName = sys.argv[1];

        try:
            with open(inputFileName, "r") as dolmadeFile:
                cmdarg = list()
                while True:
                    line = dolmadeFile.readline();
                    if line:
                        if line.strip().startswith('#'):
                            continue
                        if line.startswith((' ','\t')) and not line.strip() == "":
                            cmdarg.append(line.strip())
                        else:
                            self.executeCmd(cmdarg)
                            cmdarg = list()
                            cmdarg.append(line.strip())
                    else:
                        break

                self.executeCmd(cmdarg)

        except (IOError, OSError):
            print("ERROR: Cannot open " + inputFileName)

        self.dolmade.build()

    def start(self):
        """Program start and exception handling"""
        try:
            createDirectories()
            exit_status = self.execute()
        except (KeyboardInterrupt, SystemExit):
            self.cleanup()
            return 1
        except:
            self.cleanup()
            raise
        else:
            self.cleanup()
            return exit_status

    def cleanup(self):
        print("Deleting all temporary files...")


if __name__ == "__main__":
    sys.exit(Main().start())
