#!/usr/bin/env python

import shutil
import stat
import getpass
import sys
import subprocess
import os
import re
import hashlib

START_PATH = os.path.dirname(os.path.realpath(sys.argv[0]))
DOLMADES_PATH = os.path.expanduser('~')+'/.dolmades'

REPO_PATH = DOLMADES_PATH + "/repo"
ICON_PATH = DOLMADES_PATH + "/icons"
INST_PATH = DOLMADES_PATH + "/install"

class color:
   PURPLE = '\033[95m'
   CYAN = '\033[96m'
   DARKCYAN = '\033[36m'
   BLUE = '\033[94m'
   GREEN = '\033[92m'
   YELLOW = '\033[93m'
   RED = '\033[91m'
   BOLD = '\033[1m'
   ITALIC = '\033[3m'
   UNDERLINE = '\033[4m'
   END = '\033[0m'

def printb(str):
    print(color.BOLD + str + color.END)

def printit(str):
    print(color.ITALIC + str + color.END)

def printu(str):
    print(color.UNDERLINE + str + color.END)

class GameElement(object):
    def __init__(self):
        self.elemId = ""
        self.name = ""
        self.path = ""
        self.size = ""
        self.updated = "" 
        self.language = ""

class GameEntry(object):

    def __init__(self):
        self.gamename = ""
        self.productId = ""
        self.title = ""
        self.icon = ""
        self.elements = []

    def exists(self, elemId):
        for element in self.elements:
            if (element.elemId == elemId):
                return True
        return False

    def add(self, gameElement):
        if self.exists(gameElement.elemId):
            print("Game Element exists already, not adding it")
        else:
            self.elements.append(gameElement)

class GameList(object):

    def __init__(self):
        self.games = []

    def exists(self, pId_or_gn):
        for game in self.games:
            if (game.productId == pId_or_gn) or (game.gamename == pId_or_gn):
                return True
        return False

    def select(self, pId_or_gn):
        if self.exists(pId_or_gn):
            i = 0
            for game in self.games:
                if (game.productId == pId_or_gn) or (game.gamename == pId_or_gn):
                    self.selectedGame = i;
                    return True
                i = i+1
        return False

    def add(self, gameEntry):
        if self.exists(gameEntry.productId):
            print("Game exist already, not adding it")
            return False

        self.games.append(gameEntry)
        # select the most recently added game
        self.select(gameEntry.productId)
        return True

    def addElement(self, gameElement):
        self.games[self.selectedGame].add(gameElement)

    def getSelectedGame(self):
        return self.games[self.selectedGame]

    def readList(self, fn):
        with open(fn) as f:
            gameEntry = GameEntry()
            gameElem = GameElement()
            while True:
                line = f.readline()

                if not line:
                    break

                line = line.strip()

                if line.startswith("gamename: "):
                    gameEntry.gamename = line.replace("gamename: ","")
                if line.startswith("product id: "):
                    gameEntry.productId = line.replace("product id: ", "")
                if line.startswith("title: "):
                    gameEntry.title = line.replace("title: ", "")
                if line.startswith("icon: "):
                    gameEntry.icon = line.replace("icon: ", "")
                    self.add(gameEntry)
                    gameEntry = GameEntry()

                if line.startswith("id: "):
                    gameElem.elemId = line.replace("id: ","")
                if line.startswith("name: "):
                    gameElem.name= line.replace("name: ","")
                if line.startswith("path: "):
                    gameElem.path = line.replace("path: ","").split("/")[-1]
                if line.startswith("size: "):
                    gameElem.size = line.replace("size: ","")
                if line.startswith("updated: "):
                    gameElem.updated = line.replace("updated: ","")
                if line.startswith("language: "):
                    gameElem.language = line.replace("language: ","")
                    self.addElement(gameElem)
                    gameElem = GameElement()


class Main(object):
    udockerCmd =  START_PATH + "/udocker --quiet --repo="+REPO_PATH

    def __init__(self):
        self.prepareDirectories()
        #self.prepareRuntime()

    def prepareDirectories(self):
        untouched = True
        if (not os.path.exists(DOLMADES_PATH)):
            os.mkdir(DOLMADES_PATH, 0755)
            untouched = False
        try:
            if (os.path.exists(REPO_PATH)):
                os.rmdir(REPO_PATH)
                untouched = False
        except:
            pass

        if (not os.path.exists(REPO_PATH)):
            cmd = START_PATH + "/udocker mkrepo "+REPO_PATH
            print(cmd)
            subprocess.call(cmd, shell=True, close_fds=True)
            untouched = False
        
        if (not os.path.exists(ICON_PATH)):
            os.mkdir(ICON_PATH, 0755)
            untouched = False
        if (not os.path.exists(INST_PATH)):
            os.mkdir(INST_PATH, 0755)
            untouched = False
        if (untouched):
            printit("Found dolmade repo under " + REPO_PATH)
        else:
            printit("Initialized dolmade repo under " + REPO_PATH)

    def prepareRuntime(self):
        cmd = self.udockerCmd+" pull dolmades/dolmades-docker:runtime"
        print("Pulling dolmades runtime container...")
        subprocess.call(cmd, shell=True, close_fds=True)

        cmd = self.udockerCmd + " rm dolmades-runtime"
        subprocess.call(cmd, shell=True, close_fds=True)

        cmd = self.udockerCmd + " create --name=dolmades-runtime dolmades/dolmades-docker:runtime"
        subprocess.call(cmd, shell=True, close_fds=True)
        print("done")

    def setGameTitle(self, title):
        gameTitle=title

    def downloadIngredients(self):
        printb("downloading ingredients for "+gameTitle)

    def updateGameList(self):
        printb("Fetching detailed info about games from GOG...")

        cmd = self.udockerCmd+" run -i -t --user=$(whoami) --bindhome --hostauth dolmades-runtime lgogdownloader --list-detail --platform l --exclude c,d,e > "+DOLMADES_PATH+"/gog.l.lst"
        print("Retrieving detailed linux game list...")
        subprocess.call(cmd, shell=True, close_fds=True)

        cmd = self.udockerCmd+" run -i -t --user=$(whoami) --bindhome --hostauth dolmades-runtime lgogdownloader --list-detail --platform l,w --exclude c,d,e > "+DOLMADES_PATH+"/gog.lw.lst"
        print("Retrieving detailed linux/windows game list...")
        subprocess.call(cmd, shell=True, close_fds=True)

        cmd = self.udockerCmd+" run -i -t --user=$(whoami) --bindhome --hostauth dolmades-runtime lgogdownloader --list-detail --platform w --exclude c,d,e > "+DOLMADES_PATH+"/gog.w.lst"
        print("Retrieving detailed windows game list...")
        subprocess.call(cmd, shell=True, close_fds=True)

        self.readGameList()

        printb("done!")

    def readGameList(self):
        # FIXME check that game list files exist, if not call updateGameList() beforehand
        self.winGames = []
        winGames = subprocess.check_output(["grep", 'gamename: ',DOLMADES_PATH+"/gog.lw.lst"]).split("\n")
        for winGame in winGames:
            self.winGames.append(winGame.replace("gamename: ",""))
        self.linGames = []
        linGames = subprocess.check_output(["grep", 'gamename: ',DOLMADES_PATH+"/gog.l.lst"]).split("\n")
        for linGame in linGames:
            self.linGames.append(linGame.replace("gamename: ",""))

    def showAvailableGames(self):
        if (self.showLinuxGames):
            printit("Windows games available on this account (bold: no linux installer available)")
        else:
            printit("Windows games available on this account which have no linux installer available")

        try:
            winGames = GameList()
            winGames.readList(DOLMADES_PATH+"/gog.lw.lst")
            linGames = GameList()
            linGames.readList(DOLMADES_PATH+"/gog.l.lst")
        except:
            printb("ERROR could not read game lists, run with -u")
            return

        for winGame in winGames.games:
            if (linGames.exists(winGame.productId)):
                if (self.showLinuxGames):
                    print(winGame.gamename)
            else:
                print(color.BOLD + winGame.gamename + color.END)
            #for elem in winGame.elements:
            #    printit( " "+elem.elemId+ " - "+elem.path+" - "+elem.name)

    def printHelp(self):
        printu("Usage:")
        print(" no arguments:" + color.ITALIC + " show all available win-only games" + color.END)
        print(" -l:" + color.ITALIC + " show also games that have a linux installer" + color.END)
        print(" -h:" + color.ITALIC + " print this help" + color.END)
        print(" -u:" + color.ITALIC + " update the dolmade runtime container and the GOG game list" + color.END)
        print(" -d=gameid:" + color.ITALIC + " generate a Dolmadefile for the game 'gameid' and download its ingredients" + color.END)

    def downloadIngredients(self, i):
        print("Downloading "+i+"...")
        cmd = self.udockerCmd+" run -i -t --user=$(whoami) --bindhome --hostauth dolmades-runtime lgogdownloader --download-file "+i+" --directory "+INST_PATH
        subprocess.call(cmd, shell=True, close_fds=True)

    def computeChecksum(self, filename):
        cmd = "sh -c 'sha256sum \""+filename+"\"|cut -f 1 -d \" \"'"
        chksum = subprocess.check_output(cmd, shell=True, close_fds=True, stderr=subprocess.STDOUT)
        return chksum

    def findInstaller(self, elems):
        for elem in elems:
            # FIXME dont know if this is a valid assumption...
            if elem.elemId == "en1installer0":
                return elem.path.split("/")[-1]
        printb("Bad! No installer found")
        return None


    def generateDolmadefile(self, gamename):
        try:
            games = GameList()
            games.readList(DOLMADES_PATH+"/gog.lw.lst")
        except:
            printb("ERROR could not read game lists, try to run with -u")

        if not games.select(gamename):
            print(gamename+" not found, stopping")
            return False

        game = games.getSelectedGame()

        print("Generating Dolmadefile for "+gamename)
                
        dolmadefile = open(game.gamename+".dolmade","w")
        dolmadefile.write("# Name of the Dolmade\n")
        dolmadefile.write("DOLMADE\n")
        dolmadefile.write("    "+game.title.replace(' ','_')+"\n\n")
        
        dolmadefile.write("# Docker image used as a base\n")
        dolmadefile.write("BASE\n")
        dolmadefile.write("    dolmades/dolmades-docker:winestable\n\n")

        dolmadefile.write("# Ingredients: sha256 / file name / display name / URL #1 / URL #2 / ...\n")
        dolmadefile.write("INGREDIENT\n")
        cmd = "sh -c 'curl -s "+game.icon+"|sha256sum|cut -f 1 -d \" \"'"
        chksum = subprocess.check_output(cmd, shell=True, close_fds=True, stderr=subprocess.STDOUT)
        dolmadefile.write("    "+chksum)
        icon_fn = game.icon.split("/")[-1]
        dolmadefile.write("    "+icon_fn+"\n")
        dolmadefile.write("    Game Icon\n")
        dolmadefile.write("    "+game.icon+"\n\n")

        ingredients=None
        for elem in game.elements:
            if ingredients:
                ingredients=ingredients+","+game.gamename+"/"+elem.elemId
            else:
                ingredients=game.gamename+"/"+elem.elemId

        self.downloadIngredients(ingredients)

        for elem in game.elements:
            dolmadefile.write("INGREDIENT\n")
            ingredient=game.gamename+"/"+elem.elemId
            chksum=self.computeChecksum(INST_PATH+"/"+elem.path)
            dolmadefile.write("    "+chksum)
            dolmadefile.write("    "+elem.path+"\n")
            dolmadefile.write("    "+elem.name+"\n")
            dolmadefile.write("    gog://"+game.gamename+"/"+elem.elemId+"\n\n")

        dolmadefile.write("# Post-install custom packages like so\n")
        dolmadefile.write("#RUNROOT\n")
        dolmadefile.write("#    apt-get update && apt-get -y install custompkg && && apt-get clean && rm -rf /var/lib/apt/lists/*\n\n")

        dolmadefile.write("# Perform installation\n")
        dolmadefile.write("RUNUSER\n")
        dolmadefile.write("    wine \""+self.findInstaller(game.elements)+"\"\n\n")

        dolmadefile.write("# Set icon for the Desktop shortcut\n")
        dolmadefile.write("ICON\n")
        dolmadefile.write("    "+icon_fn+"\n\n")

        dolmadefile.write("# Set the executable\n")
        dolmadefile.write("SETTARGET\n")
        dolmadefile.write("    echo \"$(find /wineprefix/ -name bsengine.exe)\"\n")
        return True

    def start(self):
        self.showLinuxGames = False
        for arg in sys.argv:
            if (arg == '-u'):
                self.prepareRuntime()
                self.updateGameList()
            if (arg == '-l'):
                self.showLinuxGames = True
            if (arg == '-h'):
                self.printHelp()
                return
            if (arg.startswith('-d=')):
                gamename = arg.replace('-d=','')
                self.generateDolmadefile(gamename)
                return

        self.showAvailableGames()


if __name__ == "__main__":
    sys.exit(Main().start())
