#!/bin/bash

metadir="/.dolmades"
icondir="$metadir/icons"

dolmaName="$(cat $metadir/Dolmafile | grep -A1 DOLMA | tail -n1 | tr -cd '[:print:]' | sed 's/^ *//g')"
dolmaIcon="$metadir/icon.png"

# gives trouble with some applications
# and it is needed for winetricks only
unset $XDG_CACHE_HOME

if [ -f $metadir/start.sh ]; then
   echo "Start script found, using it in combination with taskbar wrapper..."
else
   echo "No start script found, using target launcher..."
   /usr/local/bin/targetLauncher
   exit
fi

# create a FIFO file, used to manage the I/O redirection from shell
PIPE=$(mktemp -u --tmpdir ${0##*/}.XXXXXXXX)
mkfifo $PIPE

# attach a file descriptor to the file
exec 3<> $PIPE

function on_click() {
    yad --window-icon="$dolmaIcon" --sticky --on-top --width=600 --height=400 --center --form --field="$dolmaName is running $1:TXT" "$(cat $metadir/run.log)" --button="OK!$icondir/ok.svg" --auto-close --kill-parent --image="$dolmaIcon"
}

export -f on_click
export dolmaName
export dolmaIcon
export metadir
export icondir

# install a notification icon for the duration of the run
yad --notification --image="$icondir/run.svg" --listen \
    --text "Dolma $dolmaName is running..." \
    --menu "Kill it!wineserver --kill!$icondir/cancel.svg" \
    --no-middle \
    --command="bash -c on_click" \
    <&3 &


# add handler to manage process shutdown
function on_exit() {
    echo "quit" >&3
    rm -f $PIPE
}
trap on_exit EXIT

$metadir/start.sh &> "$metadir/run.log"

echo "icon:$icondir/cancel.svg" >&3
echo "tooltip:Shutting down $dolmadeName..." >&3

wineserver -w
